# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1():
  def test_1(self):
    self.driver = webdriver.Chrome()
    self.driver.get("http://portal-ehouse-java.itheima.net/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, ".logout > span:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logout > span:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "首页").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btns").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btns")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".wait:nth-child(1) .el-button > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--default > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wait:nth-child(2) .el-button > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--default").click()
    self.driver.find_element(By.CSS_SELECTOR, ".logout > span:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".check:nth-child(1) > .spec").click()
    self.driver.find_element(By.CSS_SELECTOR, ".switch > span:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".switch > span:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".check:nth-child(1) > .spec").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-button > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".spec").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button > span").click()

